### ISSUE TITLE
Error starting integration at 2024.11.0

### ISSUE THREAD

**Issue by grego1981** [nos86/hacs-modbus-logo#45]
## System Information

version | core-2024.11.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.54-haos
arch | x86_64
timezone | Europe/Athens
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4994
Installed Version | 2.0.1
Stage | running
Available Repositories | 1464
Downloaded Repositories | 12

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.2
-- | --
update_channel | stable
supervisor_version | supervisor-2024.11.2
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 196.2 GB
disk_used | 25.2 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | kvm
board | ova
supervisor_api | ok
version_api | ok
installed_addons | MariaDB (2.7.1), File editor (5.8.0), ESPHome (2024.10.2), Mosquitto broker (6.4.1), Terminal & SSH (9.15.0), Samba share (12.3.2), phpMyAdmin (0.10.0), Custom deps deployment (1.3.4), DHCP server (1.4.0), Dnsmasq (1.8.1), Core DNS Override (0.1.1), Node-RED (18.1.1), Advanced SSH & Web Terminal (19.0.0), InfluxDB (5.0.1), Studio Code Server (5.17.2), Grafana (10.1.3)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 4
views | 10
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | October 30, 2024 at 1:46 PM
-- | --
current_recorder_run | November 7, 2024 at 8:50 AM
estimated_db_size | 4315.59 MiB
database_engine | mysql
database_version | 10.11.6

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

It will not start, the error in the logs below maybe related to changes in https://github.com/home-assistant/core/pull/128932

### Reproduction steps

1. Update to 24.11 from latest 24.10
2. Will not start error in logs as below

### Debug logs

```text
Logger: homeassistant.setup
Source: setup.py:334
First occurred: 8:51:40 AM (1 occurrences)
Last logged: 8:51:40 AM

Setup failed for custom integration 'modbus_logo': Unable to import component: cannot import name 'CONF_RETRIES' from 'homeassistant.components.modbus.const' (/usr/src/homeassistant/homeassistant/components/modbus/const.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1011, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1071, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/modbus_logo/__init__.py", line 16, in <module>
    from homeassistant.components.modbus.const import (
ImportError: cannot import name 'CONF_RETRIES' from 'homeassistant.components.modbus.const' (/usr/src/homeassistant/homeassistant/components/modbus/const.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1031, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1023, in async_get_component
    comp = self._get_component()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1071, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/modbus_logo/__init__.py", line 16, in <module>
    from homeassistant.components.modbus.const import (
ImportError: cannot import name 'CONF_RETRIES' from 'homeassistant.components.modbus.const' (/usr/src/homeassistant/homeassistant/components/modbus/const.py)
```

**Comment by grego1981** [comment]
Just as a crude hack I commented out CONF_RETRIES from __init__.py lines 30 and 99 and after restart everything seems to work as indented.

**Comment by nos86** [comment]
Hello @grego1981,
thank you for reporting the issue.

Looking at upstream, issue has been generated by some changes on HomeAssistant Core documented in this PR: https://github.com/home-assistant/core/pull/128932

I'm going to release the new version 0.2.2 as fix for this issue. It will be available in a couple of hours.
